- name: blockinfile example
  hosts: all
  become: yes
  tasks:
    - name: Add configuration block
      blockinfile:
        path: /tmp/app.conf
        create: yes
        block: |
          app_name=myapp
          app_env=dev
          app_port=8080
    - name: Add app config block # Custom Markers
      blockinfile:
        path: /mnt/app2.conf
        marker: "# {mark} APP CONFIG" 
        create: yes
        block: |
          app_port=8080
          app_env=prod
