- name: gathering facts example
  hosts: all
  gather_facts: yes

  tasks:

    - name: print os
      debug:
        msg: "The operating system is {{ ansible_distribution }}"

    - name: print ip address
      debug:
        msg: "The IP address is {{ ansible_default_ipv4.address }}"
    - name: print hostname
      debug:
        msg: "The hostname is {{ ansible_hostname }}"