- name: condition example
  hosts: all

  tasks:

    - name: print ubuntu
      debug:
        msg: "This is Ubuntu"
      when: (ansible_distribution == "Ubuntu") and (ansible_distribution_version == "2.04")

    - name: print centos
      debug:
        msg: "This is CentOS"
      when: ansible_distribution == "CentOS"

    - name: print amazon linux
      debug:
        msg: "Wellcom to amazon linux"
      when: ansible_distribution == "Amazon" 