- name:
  hosts: all

  tasks:
    - name:  print fruit list
      debug:
        msg: "{{ item }}"
      loop:
        - apple
        - banana
        - cherry
        - mango
        - orange

    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl
        - vim
        - wget
        - tree
      become: yes