- name: variable example
  hosts: all
  vars:
    url: "https://golobl.variable.com"
  vars_files:
    - ./variables.txt
  tasks:
    - name: print url variable
      debug:
        msg: "The URL is {{ url }}"

    - name: print url variable
      debug:
        msg: "The URL is {{ url }}"


    - name: print url variable
      debug:
        msg: "The URL is {{ url }}"
      vars:
        url: "https://local.variable.com"