- name: install java
  package:
    name: java
    state: present

- name: install openjdk-21-jdk
  package:
    name: openjdk-8-jdk
    state: present

- name: download and extract application file
  unarchive:
    src: "{{ URL }}"
    dest: "/opt/"
    remote_src: yes

- name: start tomcat server
  command: "/opt/{{ TOMCAT_DIR }}/bin/catalina.sh run"
  