- name: install openjdk-8-jdk
  package:
    name: openjdk-8-jdk
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: download and extract tomcat file
  unarchive:
    src: "{{ URL }}"
    dest: "/opt/"
    remote_src: yes
  when: ansible_facts['os_family'] == "Debian"

- name: upload application daemon file
  copy:
    src: tomcat-init
    dest: /etc/init.d/tomcatd
    mode: '0755'
  when: ansible_facts['os_family'] == "Debian"

- name: start tomcat service
  systemd:
        daemon_reload: true
        name: tomcatd
        state: started
  when: ansible_os_family == "Debian"
  tags: start-tomcat

#- name: student app deployment
#  copy:
#    src: student.war
#    dest: /opt/apache-tomcat-9.0.113/webapps/
#  tags: deploy-app
#  when: ansible_facts['os_family'] == "Debian"

# advance way to download from url to destination
- name: student app deployment
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war
    dest: "{{ WEB_APP_DIR }}/student.war"
  tags: deploy-app
  when: ansible_facts['os_family'] == "Debian"