    - name: Install httpd
      package:
        name: "{{PKG}}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Selinux permissive mode
      selinux:
        policy: targeted
        state: permissive
      when: ansible_os_family == "RedHat"

    - name: proxy configuration
      copy:
        src: proxy.conf
        dest: /etc/httpd/conf.d/proxy.conf
      notify: restart Apache service
      when: ansible_os_family == "RedHat"

#    - name: Start and enable Apache service
#      systemd:
#        name: "{{PKG}}"
#        state: started
#        enabled: yes
#      when: ansible_os_family == "RedHat"