    - name: Install httpd
      package:
        name: "{{PKG}}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: proxy configuration
      copy:
        src: proxy.conf
        dest: /etc/httpd/conf.d/proxy.conf
      when: ansible_os_family == "RedHat"

    - name: Deploy proxy configuration
      copy:
        src: proxy.conf
        dest: /etc/httpd/conf.d/proxy.conf

    - name: Start and enable Apache service
      systemd:
        name: "{{PKG}}"
        state: started
        enabled: yes
